app_homepage:
    path: /
    controller: App\Controller\PageController::showAction
    defaults:
        id: 1

app_pages:
    prefix: /pages
    resource: "Routes/pages.yaml"
    name_prefix: app_pages_

app_posts:
    prefix: /posts
    resource: "Routes/posts.yaml"
    name_prefix: app_posts_

app_tags:
    prefix: /tags
    resource: "Routes/tags.yaml"
    name_prefix: app_tags_

app_actualites:
    prefix: /actualites
    resource: "Routes/actualites.yaml"
    name_prefix: app_actualites_

app_auteurs:
    prefix: /auteurs
    resource: "Routes/auteurs.yaml"
    name_prefix: app_auteurs_